-- ============================================================
-- 论坛升级脚本：验证码登录 + 个人资料/头像 + 分区 + 管理员
-- 使用方法：Supabase -> SQL Editor -> 粘贴全部 -> Run
-- 注意：会删除并重建 posts 表（旧帖会丢失）
-- ============================================================

-- 1. 用户资料表（昵称、头像、管理员标识）
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  nickname text,
  avatar_url text,
  is_admin boolean not null default false,
  created_at timestamptz default now()
);

-- 2. 注册时自动创建资料记录的触发器
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, email, nickname)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'nickname', split_part(new.email,'@',1)))
  on conflict (id) do nothing;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- 3. profiles 权限：所有人可看，本人可改自己的
alter table public.profiles enable row level security;

drop policy if exists "资料对所有人可见" on public.profiles;
create policy "资料对所有人可见" on public.profiles for select using (true);

drop policy if exists "本人可写自己资料" on public.profiles;
create policy "本人可写自己资料" on public.profiles for insert with check (auth.uid() = id);

drop policy if exists "本人可改自己资料" on public.profiles;
create policy "本人可改自己资料" on public.profiles for update using (auth.uid() = id);

-- 4. 分区表
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz default now()
);

alter table public.categories enable row level security;

drop policy if exists "分区对所有人可见" on public.categories;
create policy "分区对所有人可见" on public.categories for select using (true);

-- 只有管理员能创建/删除分区
drop policy if exists "管理员可建分区" on public.categories;
create policy "管理员可建分区" on public.categories for insert with check (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin)
);
drop policy if exists "管理员可删分区" on public.categories;
create policy "管理员可删分区" on public.categories for delete using (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin)
);

-- 5. 重建帖子表（增加分区字段）
drop table if exists public.posts;
create table public.posts (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  author_nickname text,
  title text not null,
  content text,
  category_id bigint references public.categories(id) on delete cascade
);

alter table public.posts enable row level security;

drop policy if exists "帖子对所有人可见" on public.posts;
create policy "帖子对所有人可见" on public.posts for select using (true);

drop policy if exists "登录用户可以发帖" on public.posts;
create policy "登录用户可以发帖" on public.posts for insert with check (auth.uid() = user_id);

-- 作者和管理员都能删帖
drop policy if exists "作者可删帖" on public.posts;
create policy "作者可删帖" on public.posts for delete using (auth.uid() = user_id);

drop policy if exists "管理员可删任何帖子" on public.posts;
create policy "管理员可删任何帖子" on public.posts for delete using (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin)
);

-- 6. 头像存储桶（公开可读，本人可上传到自己的文件夹）
insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do nothing;

drop policy if exists "头像公开可读" on storage.objects;
create policy "头像公开可读" on storage.objects
  for select using (bucket_id = 'avatars');

drop policy if exists "登录用户可上传头像" on storage.objects;
create policy "登录用户可上传头像" on storage.objects
  for insert with check (bucket_id = 'avatars' and auth.uid()::text = (storage.foldername(name))[1]);

-- ============================================================
-- 7. 设置管理员（重要！）
--    把下面的邮箱换成你自己的管理员邮箱，注册过一次之后执行
-- ============================================================
-- update public.profiles set is_admin = true where email = '你的邮箱@example.com';
