-- 社区预设词表（可公开分享或仅自己可见）
-- 使用方法：Supabase -> SQL Editor -> 粘贴全部 -> Run

create table if not exists public.prompt_presets (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  author_nickname text,
  title text not null,
  content text not null,
  is_public boolean not null default true
);

alter table public.prompt_presets enable row level security;

-- 公开的预设所有人可见；自己的预设（含私有）自己可见
drop policy if exists "预设词可见性" on public.prompt_presets;
create policy "预设词可见性" on public.prompt_presets
  for select using (is_public or auth.uid() = user_id);

-- 登录用户可以上传（只能以自己名义）
drop policy if exists "登录用户可上传预设" on public.prompt_presets;
create policy "登录用户可上传预设" on public.prompt_presets
  for insert with check (auth.uid() = user_id);

-- 只能改自己的预设（用于切换公开/私有）
drop policy if exists "本人可改预设" on public.prompt_presets;
create policy "本人可改预设" on public.prompt_presets
  for update using (auth.uid() = user_id);

-- 只能删自己的预设
drop policy if exists "本人可删预设" on public.prompt_presets;
create policy "本人可删预设" on public.prompt_presets
  for delete using (auth.uid() = user_id);
