-- 选择符广场表（发布选择符合集，可一键导入到自己的选择符管理）
-- 使用方法：Supabase -> SQL Editor -> 粘贴全部 -> Run

create table if not exists public.selector_packs (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  author_nickname text,
  title text not null,
  description text,
  selectors jsonb not null
);

alter table public.selector_packs enable row level security;

-- 公开可读
drop policy if exists "选择符合集公开可读" on public.selector_packs;
create policy "选择符合集公开可读" on public.selector_packs
  for select using (true);

-- 登录用户以自己名义发布
drop policy if exists "登录用户可发布选择符" on public.selector_packs;
create policy "登录用户可发布选择符" on public.selector_packs
  for insert with check (auth.uid() = user_id);

-- 只能删自己的
drop policy if exists "本人可删选择符合集" on public.selector_packs;
create policy "本人可删选择符合集" on public.selector_packs
  for delete using (auth.uid() = user_id);
